# Generated by Django 6.0 on 2026-01-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cliente_produto_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='datanasc',
            field=models.DateField(default='12/02/1997', verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=15, verbose_name='C.P.F'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
