# Generated by Django 6.0 on 2026-01-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cliente_datanasc_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='img_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
